//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_Recrutement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dde_Recrutement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dde_Recrutement()
        {
            this.Status_Dde = new HashSet<Status_Dde>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_Dde { get; set; }
        public string Nom_Emp { get; set; }
        public string Fonction_Emp { get; set; }
        public string Type_Dde { get; set; }
        public string Nbre_Poste { get; set; }
        public string Remplacemnt { get; set; }
        public string File_Name { get; set; }
        public string File_Path { get; set; }
        public string Nature_Contrat { get; set; }
        public string Diplome { get; set; }
        public Nullable<int> NB_année { get; set; }
        public string Affectation { get; set; }
        public string Remarque { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status_Dde> Status_Dde { get; set; }
    }
}
