//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_Recrutement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employé
    {
        public int Id { get; set; }
        public string Matricule { get; set; }
        public string Nom_prenom { get; set; }
        public string E_mail { get; set; }
        public string Fonction { get; set; }
        public string Responsable { get; set; }
        public Nullable<int> Id_role { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
